### PR TITLE
Add proxy config to Downloader

### PR DESCRIPTION
**Pull request by scobal**
Hello,

I'd like to be able to use embedded mongo from behind a proxy. This PR allows configuration by command line parameters, eg:

mvn clean package -Dhttp.proxyHost=www.proxy.com -Dhttp.proxyPort=8000

### CODE REVIEW

**Comment by mrfarhadi** [comment]
Hello!
I have the same problem. I would like to use flapdoodle mongo behind a proxy. It cannot open the stream "http://fastdl.mongodb.org/linux/mongodb-linux-i686-3.0.5.tgz", although, the proxy is set for Java. Any way to fix this issue without inserting any code as configuration? The above commands did not work neither.

**Comment by matlockx** [comment]
@michaelmosmann state here?

**Comment by michaelmosmann** [comment]
This is implemented in an different way now. Thanks for your input ...

**Comment by nabilm2i** [comment]
i have the same issue on my project CI/CD.. But locally it works.
I wonder what am i missing?
Any ideas?
I am using flapdoodle 3.0.0.

**Comment by michaelmosmann** [comment]
Is there any chance to use the new release?

**Pull request closed without merging**
