### PR TITLE
Remove dependency on commons-io

### PR DESCRIPTION
**Pull request by adamretter**
Uses Java's NIO.2 instead.

Attempting to solve issues such as: https://github.com/joelittlejohn/embedmongo-maven-plugin/issues/44

### CODE REVIEW

**Comment by Loki-Afro** [comment]
@adamretter embedmongo-maven-plugin seems to use process 2.x you made your changes in 3.x, was this intended?

**Comment by adamretter** [comment]
Well I think we would also update embedmongo-maven-plugin to the latest
versions of anything too.

Do you also want me to send a PR to backport for 2.x?

**Comment by adamretter** [comment]
@Loki-Afro Let me know which you want to go on this. We have a project waiting by @dizzzz the changes.

**Comment by Loki-Afro** [comment]
@adamretter yes please backport it first, i don't know when a new process lib will be released, sorry for the late reply.

**Comment by adamretter** [comment]
@dizzzz I think you need to be clear that you mean version 0.4.0 of the project embedmongo-maven-plugin, which has a dependency on this.

**Comment by adamretter** [comment]
@Loki-Afro As requested here is the port to the `process-2.x.x` branch - https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/pull/82

**Comment by dizzzz** [comment]
Adam, you are right. I found out about the ‘layering ‘ a bit later

**Pull request merged**
